# Generated by Django 3.0.3 on 2020-04-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_type', models.CharField(max_length=10)),
                ('occupation_name', models.CharField(max_length=20)),
                ('occupation_address', models.CharField(max_length=30)),
                ('occupation_phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_name', models.CharField(max_length=30)),
                ('residence_address', models.CharField(max_length=30)),
                ('residence_city', models.CharField(max_length=20)),
                ('residence_state', models.CharField(max_length=20)),
                ('residence_pincode', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('rent', models.IntegerField()),
                ('image', models.ImageField(upload_to='Residences')),
            ],
        ),
        migrations.CreateModel(
            name='User_role_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=30)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('occupation_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Occupation')),
                ('user_role_type_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.User_role_type')),
            ],
        ),
        migrations.CreateModel(
            name='Residence_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(max_length=7)),
                ('residence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Residence')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=30)),
                ('residence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Residence')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stay_duration', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('residence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Residence')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.User')),
            ],
        ),
    ]
