# Generated by Django 3.0.3 on 2020-06-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHomesAdmin', '0002_auto_20200627_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_name', models.CharField(max_length=30)),
                ('residence_address', models.CharField(max_length=30)),
                ('residence_city', models.CharField(max_length=20)),
                ('residence_state', models.CharField(max_length=20)),
                ('residence_pincode', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('rent', models.IntegerField()),
                ('image', models.ImageField(upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Residence_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(max_length=7)),
                ('residence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Residence')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=30)),
                ('residence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Residence')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='residence_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.Residence'),
            preserve_default=False,
        ),
    ]
