# Generated by Django 3.0.3 on 2020-06-29 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHomesAdmin', '0005_auto_20200629_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role_type_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User_role_type',
        ),
    ]
