# Generated by Django 3.0.3 on 2020-06-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHomesAdmin', '0006_auto_20200629_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupation_id',
        ),
        migrations.AddField(
            model_name='occupation',
            name='user_id',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='HappyHomesAdmin.User'),
        ),
    ]
